### ISSUE TITLE
1 nice Doku

### ISSUE THREAD

**Issue by TheBirdsAreSpies** [SvenWollinger/ReviewYou#5]
Wir brauchen 1 nice Doku

**Comment by TheBirdsAreSpies** [comment]
wo bleibt doku

**Comment by SvenWollinger** [comment]
![](https://video-cdn-eu-west-1.ziggeo.com/v1/applications/r1c3b7c5f44d5717525b4e814d88c6b6/videos/r112500e86459daa4580fa35aac2f3f9/image?effect_profile=r179bed90e74989804c860aa90b3745a&force_refresh=false)
